name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Android Github Action
      uses: Vukan-Markovic/Github-Android-Action@1.2
